services:
  db:
    image: mariadb:11
    container_name: example003_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ci4_app
      MARIADB_USER: ci4_user
      MARIADB_PASSWORD: ci4_pass
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: example003_app
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      database.default.hostname: db
      database.default.database: ci4_app
      database.default.username: ci4_user
      database.default.password: ci4_pass
      database.default.port: 3306
      database.default.DBDriver: MySQLi
      XDEBUG_MODE: coverage
    volumes:
      - ./:/var/www/html
    command: sh /var/www/html/build/start-app.sh
